services:

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  celery_worker:
    build: .
    working_dir: /app/celery_example
    command: celery -A celery_example worker --loglevel=info  # NOTE: Changed to project
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    # NOTE: New Volume
    volumes:
      - data:/data

  # NOTE: New service
  web:
    build: .
    working_dir: /app/celery_example
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      celery_worker:
        condition: service_started
    # NOTE: New Volume
    volumes:
      - data:/data

volumes:
  rabbitmq_data:
  # NOTE: New Volume
  data:
    
