version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  loader:
    image: python:3.11-slim
    depends_on:
      db:
        condition: service_healthy
    working_dir: /work
    volumes:
      - ./:/work
    command:
      - sh
      - -lc
      - |
          pip install --no-cache-dir psycopg2-binary==2.9.9 python-dateutil==2.9.0.post0
          python /work/load_customers.py \
            --host db --port 5432 \
            --user postgres --password secret \
            --create-db --database julius_demo \
            --csv /work/messy_customers.csv \
            --table customers --extras 60

volumes:
  pgdata:

