# Generated by Django 5.2.8 on 2025-11-17 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready')], default='pending', max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobListingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('job_url', models.CharField(max_length=1024)),
                ('job_type', models.CharField(blank=True, max_length=1024, null=True)),
                ('level', models.CharField(blank=True, max_length=1024, null=True)),
                ('summary', models.CharField(blank=True, max_length=1024, null=True)),
                ('salary', models.CharField(blank=True, max_length=1024, null=True)),
                ('posted', models.CharField(blank=True, max_length=1024, null=True)),
                ('applicants', models.IntegerField(blank=True, null=True)),
                ('llm_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listing_results', to='jobs.llmresult')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(max_length=256)),
                ('ready', models.BooleanField()),
                ('data', models.JSONField()),
                ('llm_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='jobs.llmresult')),
            ],
        ),
    ]
